name: Sync Test
on:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: test sync
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: execute
        id: execute
        with:
          server: playground.direktiv.io
          namespace: jens
          sync: tests/wf.yaml
          token: ${{ secrets.DIREKTIV_TOKEN }}
        uses: vorteil/direktiv-actions-ghsync@test
